section 'getting-started', "Getting Started" do
  topic 'home',                 'Home'
  topic 'rhodes/tutorial',      'Rhodes Tutorial'
  topic 'rhosync/tutorial',     'RhoSync Tutorial'
  topic 'rhohub/tutorial',      'RhoHub Tutorial'
  topic 'tutorials',            'How To'
  topic 'faq',                  'Frequently Asked Questions'
  topic 'secure-apps',          'Building Highly Secure Apps'
end

section 'rhodes-reference', "Rhodes Developer Reference" do
  topic 'rhodes/introduction',      'Introduction'
  topic 'rhodes/install',           'Install Rhodes'
  topic 'rhodes/generator',         'App Generator'
  topic 'rhodes/build',             'Build Application'  
  topic 'rhodes/application',       'App Structure'
  topic 'rhodes/ui',                'User Interface'
  topic 'rhodes/css-framework',     'CSS Framework'  
  topic 'rhodes/configuration',     'Configuration'
  topic 'rhodes/device-caps',       'Device Capabilities'
  topic 'rhodes/rhom',              'Local Database and Rhom'
  topic 'rhodes/synchronization',   'Synchronization'
  topic 'rhodes/connect-to-web-services', 'Connecting Directly to Web Services'
  topic 'rhodes/extensions',        'Extending the Rhodes Framework'
  topic 'rhodes/test-log-debug',    'Testing, Logging and Debugging'  
  topic 'rhodes/contributing',      'Contributing'
end

section 'rhosync-reference', "RhoSync Developer Reference" do
  topic 'rhosync/introduction',      'Introduction'
  topic 'rhosync/install',           'Installation'
  topic 'rhosync/command-line',      'App Generator and Rake Tasks'
  topic 'rhosync/source-adapters',   'Source Adapters'
  topic 'rhosync/testing',           'Testing and Debugging'
  topic 'rhosync/authentication',    'Adding Device Authentication'
  topic 'rhosync/web-console',       'Admin Web Interface'
  topic 'rhosync/licensing',         'Licensing your App'
  topic 'rhosync/deploying',         'Deployment and Hosting Options'
  topic 'rhosync/push',              'Device Push'
  topic 'rhosync/blob-sync',         'Binary Objects and Blob Sync'
  topic 'rhosync/bulk-sync',         'Big Datasets and Bulk Sync'
  topic 'rhosync/async-jobs',        'Adapter Jobs with Resque'
  topic 'rhosync/rest-api',          'RhoSync REST API'
  topic 'rhosync/metadata',          'Dynamic Views with Metadata'
  topic 'rhosync/stats-middleware',  'Collecting Runtime Stats'
  topic 'rhosync/client',            'Using RhoSync without Rhodes'
  topic 'rhosync/benchmarks',        'Benchmarks'
  topic 'rhosync/contributing',      'Contributing'
end